In [29]:
#-#-#-#-# AQUÍ EMPEZARÁN LOS ARRAYS #-#-#-#-#

In [2]:
import numpy as np

In [31]:
#HACIENDO LISTAS

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
#TRANSFORMANDO LA LISTA A ARRAYS

arreglo= np.array(numbers)

In [33]:
type(numbers)

list

In [34]:
#MIDE LA CANTIDAD DE BITS EN EL ARRAY

arreglo.dtype

dtype('int32')

In [35]:
#DEFINIENDO EL ARREGLO DE INT A FLOAT
np.array(arreglo, dtype=np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [36]:
#TRANSFORMANDO LOS DATOS EXISTENTES A FLOTANTES
arreglo.astype(np.float32)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)


<h3 style = "color:blue"><b>UN SIMPLE TÍTULO (Desglosar para ver código) </b></h3>

In [39]:
#UN RANGE ADAPTADO A UN ARRAY (NO FUNCIONA EL RANGE COMÚN)
new_array = np.arange(1,11)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#UN ARANGE PERO DE 2 EN 2
new_array2 = np.arange (1,11,2)
new_array2

array([1, 3, 5, 7, 9])

In [42]:
#SACANDO EL PROMEDIO DEL ARREGLO
promedy = np.mean(new_array)
promedy

5.5

In [45]:
#SACANDO LA MEDIANA DEL ARREGLO
median = np.median(new_array)
median

5.5

In [46]:
#RELLENANDO EL ARREGLO CON UNOS

array_ones = np.ones(10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
#PASANDO EL ARRAY DE FLOTANTES A ENTEROS
array_int_ones = array_ones.astype(int)
array_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [50]:
#UN ARRAY DE CEROS
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
#AHORA COMO EL DEL UNO, PASEMOS ESTE ARRAY DE CEROS DE FLOTANTES A ENTEROS
array_int_zeros = array_zeros.astype(int)
array_int_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
#UN ARRAY DE NÚMEROS RANDOMS
ram_array = np.random.rand(5)
ram_array

array([0.03678918, 0.38304158, 0.24384008, 0.5060054 , 0.10502932])

In [62]:
#AHORA GENEREMOS UNA MATRIZ DE 3X3. EL ARRAY ANTERIOR ERA DE UN VECTOR DE UNA DIMENSIÓN
matriz = np.random.rand(3,3)
matriz

array([[0.47610166, 0.3592635 , 0.58042274],
       [0.58246125, 0.99567392, 0.45599096],
       [0.78923803, 0.44158711, 0.94962996]])

In [4]:
#AHORA UN ARREGLO ALEATORIOS DE 10 NÚMEROS ENTEROSD DEL 1 AL 5

ram_array2 = np.random.randint(1,5,10)
ram_array2

array([3, 4, 4, 1, 4, 2, 2, 1, 2, 2])

In [84]:
#GENERANDO UNA MATRIZ ALEATORIA DE 10 NÚMEROS ENTEROS DEL 1 AL 100

matriz2 = np.random.randint(1,100,(5,5))
matriz2

array([[43, 27, 96, 24, 64],
       [42, 18,  4, 11, 36],
       [78, 18, 52, 91, 19],
       [65, 37, 28, 87, 66],
       [79, 50, 33, 15, 52]])