In [1]:
import numpy as np

In [14]:
#Generando un Array de 12 elementos con Random

array3 = np.random.randint(20,80,4)
array3

array([61, 60, 25, 35])

In [15]:
#Generando la dimensión de un arreglo

np.shape(array3)
array3

array([61, 60, 25, 35])

In [16]:
#Transformando el vector a una matriz de 2x2 con Reshape

matriz = array3.reshape(2,2)
matriz

array([[61, 60],
       [25, 35]])

In [17]:
#Creando un tensor de 3 dimensiones

tensor = [[[[4,3,2,1],[7,8,9,5]]]]
tensor

[[[[4, 3, 2, 1], [7, 8, 9, 5]]]]